function body_Jacobian_d1_ = body_Jacobian_d1(in1,in2,in3)
%BODY_JACOBIAN_D1
%    BODY_JACOBIAN_D1_ = BODY_JACOBIAN_D1(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 5.5.
%    15-Aug-2014 15:39:36

Cx1 = in3(:,1);
Cy1 = in3(:,7);
body_Jacobian_d1_ = reshape([-Cy1,Cx1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6, 6]);
