function body_Jacobian_d2_ = body_Jacobian_d2(in1,in2,in3)
%BODY_JACOBIAN_D2
%    BODY_JACOBIAN_D2_ = BODY_JACOBIAN_D2(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 5.5.
%    15-Aug-2014 15:39:36

A2 = in2(:,2);
Cx2 = in3(:,2);
Cy2 = in3(:,8);
Cz2 = in3(:,14);
L1 = in1(:,1);
L2 = in1(:,2);
t352 = cos(A2);
t353 = sin(A2);
t354 = t352-1.0;
t355 = L1.*t353;
t356 = L2.*t354;
t357 = t355+t356;
t358 = L1.*t354;
t359 = t358-L2.*t353;
body_Jacobian_d2_ = reshape([-Cy2.*t352,-t355-t356+Cx2.*t352+Cz2.*t353,-Cy2.*t353,-t353,0.0,t352,Cz2-L1.*t352-L2.*t353-t353.*t357-t352.*t359,0.0,-Cx2-t355+L2.*t352+t352.*t357-t353.*t359,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6, 6]);
