function d_inv_SJ_6_ = d_inv_SJ_6(in1,in2)
%D_INV_SJ_6
%    D_INV_SJ_6_ = D_INV_SJ_6(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.5.
%    20-May-2013 02:15:42

d_inv_SJ_6_ = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6, 6]);
