function Wd_ = EulerWd_MinF3(in1,in2,in3,in4,gr)
%EULERWD_MINF3
%    WD_ = EULERWD_MINF3(IN1,IN2,IN3,IN4,GR)

%    This function was generated by the Symbolic Math Toolbox version 5.5.
%    14-Mar-2015 10:22:03

Ld2 = in1(:,2);
Ld3 = in1(:,3);
acc1 = in4(:,1);
acc2 = in4(:,2);
acc3 = in4(:,3);
pos2 = in2(:,2);
pos3 = in2(:,3);
vel1 = in3(:,1);
vel2 = in3(:,2);
vel3 = in3(:,3);
t2 = conj(Ld2);
t3 = conj(pos2);
t4 = sin(t3);
t5 = cos(t3);
t6 = t4.*t5.*vel1.*vel2.*2.0;
t7 = t5.^2;
t8 = t4.^2;
t9 = vel2.^2;
t10 = conj(Ld3);
t11 = t10.*t5;
t12 = t11+t2;
t13 = acc1.*t2;
t14 = acc1.*t10.*t5;
t15 = t13+t14;
t16 = conj(pos3);
t17 = t16+t3;
t18 = cos(t17);
t19 = t2.*vel1;
t20 = t10.*t5.*vel1;
t21 = t19+t20;
t22 = sin(t17);
t23 = vel2+vel3;
t24 = cos(t16);
t25 = sin(t16);
t26 = t18.*t22.*t23.*vel1.*2.0;
t27 = t18.^2;
t28 = t22.^2;
t29 = t23.^2;
t30 = acc2+acc3;
t31 = vel1.^2;
t32 = t10.^2;
t33 = acc2.*t10.*t24;
t34 = t21.*t22.*vel1;
t35 = gr.*t22;
t36 = t18.*t21.*vel1;
t37 = t18.*t22.*t31;
t38 = t28.*t31;
t39 = t38-t27.*t31;
Wd_ = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,acc1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,acc1.*t2.^2,0.0,0.0,acc1.*t2.*t5.*2.0-t2.*t4.*vel1.*vel2.*2.0,-gr.*t5+t2.*t31.*t4,0.0,acc1.*t2.*t4.*-2.0-t2.*t5.*vel1.*vel2.*2.0,gr.*t4+t2.*t31.*t5,0.0,0.0,0.0,0.0,t6+acc1.*t8,-t31.*t4.*t5,0.0,-t6+acc1.*t7,t31.*t4.*t5,0.0,0.0,acc2,0.0,acc1.*t4.*t5.*2.0+t7.*vel1.*vel2.*2.0-t8.*vel1.*vel2.*2.0,-t31.*t7+t31.*t8,0.0,-acc2.*t4-t5.*t9,-acc1.*t4,0.0,-acc2.*t5+t4.*t9,-acc1.*t5,0.0,t12.*t15-t10.*t21.*t4.*vel2-t10.*t12.*t4.*vel1.*vel2,acc2.*t24.^2.*t32+acc2.*t25.^2.*t32-gr.*t10.*t18.*t24-gr.*t10.*t22.*t25+t10.*t21.*t4.*vel1,0.0,t15.*t18+acc1.*t12.*t18-t21.*t22.*t23-t12.*t22.*t23.*vel1-t10.*t18.*t4.*vel1.*vel2.*2.0,t33+t34-gr.*t18+t10.*t24.*t30+t10.*t18.*t31.*t4-t10.*t23.*t25.*vel3-t10.*t25.*vel2.*vel3,t33+t34-gr.*t18+t10.*t23.*t25.*vel2-t10.*t25.*vel2.*vel3,-t15.*t22-acc1.*t12.*t22-t18.*t21.*t23-t12.*t18.*t23.*vel1+t10.*t22.*t4.*vel1.*vel2.*2.0,t35+t36-acc2.*t10.*t25-t10.*t25.*t30-t10.*t22.*t31.*t4-t10.*t23.*t24.*vel3-t10.*t24.*vel2.*vel3,t35+t36-acc2.*t10.*t25+t10.*t23.*t24.*vel2-t10.*t24.*vel2.*vel3,-acc2.*t10.*t18.*t25+acc2.*t10.*t22.*t24+t10.*t18.*t23.*t24.*vel2+t10.*t22.*t23.*t25.*vel2-t10.*t18.*t24.*vel2.*vel3-t10.*t22.*t25.*vel2.*vel3,-acc1.*t10.*t18.*t25+acc1.*t10.*t22.*t24+t10.*t18.*t23.*t24.*vel1+t10.*t22.*t23.*t25.*vel1-t10.*t18.*t24.*vel1.*vel2-t10.*t18.*t24.*vel1.*vel3-t10.*t22.*t25.*vel1.*vel2-t10.*t22.*t25.*vel1.*vel3,0.0,t26+acc1.*t28,-t18.*t22.*t31,-t37,-t26+acc1.*t27,t37,t37,0.0,t30,t30,acc1.*t18.*t22.*2.0+t23.*t27.*vel1.*2.0-t23.*t28.*vel1.*2.0,t39,t39,-t18.*t29-t22.*t30,-acc1.*t22,-acc1.*t22,-t18.*t30+t22.*t29,-acc1.*t18,-acc1.*t18],[3, 30]);
