function Wm = EulerWm(in1,in2,in3,in4,in5)
%EULERWM
%    WM = EULERWM(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 5.5.
%    12-Jun-2014 15:18:23

acc1 = in5(:,1);
acc2 = in5(:,2);
acc3 = in5(:,3);
acc4 = in5(:,4);
acc5 = in5(:,5);
acc6 = in5(:,6);
k1 = in2(:,1);
k2 = in2(:,2);
k3 = in2(:,3);
k4 = in2(:,4);
k5 = in2(:,5);
k6 = in2(:,6);
pos2 = in3(:,2);
pos3 = in3(:,3);
pos4 = in3(:,4);
vel1 = in4(:,1);
vel2 = in4(:,2);
vel3 = in4(:,3);
vel4 = in4(:,4);
vel5 = in4(:,5);
vel6 = in4(:,6);
t2 = sin(pos4);
t3 = pos2+pos3;
t4 = cos(t3);
t5 = t2.*vel2;
t6 = t2.*vel3;
t7 = cos(pos4);
t8 = t5+t6-t4.*t7.*vel1;
t9 = conj(vel2);
t10 = conj(pos4);
t11 = cos(t10);
t12 = conj(pos2);
t13 = conj(pos3);
t14 = t12+t13;
t15 = conj(vel1);
t16 = t11.*t9;
t17 = conj(vel3);
t18 = t11.*t17;
t19 = sin(t10);
t20 = cos(t14);
t21 = t15.*t19.*t20;
Wm = reshape([k1.*conj(acc1).*conj(k1),0.0,0.0,0.0,0.0,0.0,0.0,k2.*conj(acc2).*conj(k2),0.0,0.0,0.0,0.0,0.0,acc3.*k3,k3.*(t9+conj(acc3).*conj(k3)),0.0,0.0,0.0,0.0,0.0,k4.*t4.*vel1.*vel4,-k4.*(t15.*sin(t14)-conj(acc4).*conj(k4)),0.0,0.0,0.0,0.0,0.0,k5.*t8.*vel5-k6.*t8.*vel6,k5.*(t16+t18+t21+conj(acc5).*conj(k5)),0.0,0.0,0.0,0.0,0.0,0.0,-k6.*(t16+t18+t21-conj(acc6).*conj(k6))],[6, 6]);
