function gst3 = fwd_kin3(in1,in2)
%FWD_KIN3
%    GST3 = FWD_KIN3(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.5.
%    24-Apr-2013 12:50:29

A1 = in2(:,1);
A2 = in2(:,2);
A3 = in2(:,3);
L1 = in1(:,1);
L2 = in1(:,2);
L3 = in1(:,3);
L4 = in1(:,4);
t61 = A2+A3;
t62 = cos(A1);
t63 = sin(t61);
t64 = cos(t61);
t65 = sin(A1);
t66 = L4.*t63;
t67 = sin(A2);
t68 = L3.*t67;
t69 = L2+t66+t68;
gst3 = reshape([t62.*t64,t64.*t65,-t63,0.0,-t65,t62,0.0,0.0,t62.*t63,t63.*t65,t64,0.0,t62.*t69,t65.*t69,L1+L4.*t64+L3.*cos(A2),1.0],[4, 4]);
