function gst2 = fwd_kin2(in1,in2)
%FWD_KIN2
%    GST2 = FWD_KIN2(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.5.
%    24-Apr-2013 12:50:05

A1 = in2(:,1);
A2 = in2(:,2);
L1 = in1(:,1);
L2 = in1(:,2);
L3 = in1(:,3);
t54 = cos(A1);
t55 = sin(A2);
t56 = cos(A2);
t57 = sin(A1);
t58 = L3.*t55;
t59 = L2+t58;
gst2 = reshape([t54.*t56,t56.*t57,-t55,0.0,-t57,t54,0.0,0.0,t54.*t55,t55.*t57,t56,0.0,t54.*t59,t57.*t59,L1+L3.*t56,1.0],[4, 4]);
