function gst1 = fwd_kin1(in1,in2)
%FWD_KIN1
%    GST1 = FWD_KIN1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.5.
%    24-Apr-2013 12:49:35

A1 = in2(:,1);
L1 = in1(:,1);
L2 = in1(:,2);
t51 = cos(A1);
t52 = sin(A1);
gst1 = reshape([t51,t52,0.0,0.0,-t52,t51,0.0,0.0,0.0,0.0,1.0,0.0,L2.*t51,L2.*t52,L1,1.0],[4, 4]);
